### ISSUE TITLE
Node 17: Could not connect to db error

### ISSUE THREAD

**Issue by replete** [TomDoesTech/Testing-Express-REST-API#2]
## Environment
* node v17.0.1
* npm 8.1.0
* MongoDB 5.0.3 community edition installed from homebrew
* macos catalina 10.15.7

## Repro
```
git clone git@github.com:TomDoesTech/Testing-Express-REST-API.git
cd Testing-Express-REST-API
npm i
(make sure mongodb is ready)
npm run dev
(then this following error in the console after around 30s)
```

## Error
```
> rest-api-tutorial-updated@1.0.0 dev
> ts-node-dev --respawn --transpile-only src/app.ts

[INFO] 02:35:24 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.3)
[2021-10-24T02:35:26+01:00] INFO: App is running at http://localhost:1337
[2021-10-24T02:35:56+01:00] ERROR: Could not connect to db
```

## Workaround attempt
Removing `async` and `await` from the `connect` code appears to solve the problem at first glance.

```diff
diff --git a/src/app.ts b/src/app.ts
index 4a714e0..7b50c07 100644
--- a/src/app.ts
+++ b/src/app.ts
@@ -8,8 +8,8 @@ const port = config.get<number>("port");
 
 const app = createServer();
 
-app.listen(port, async () => {
+app.listen(port, () => {
   logger.info(`App is running at http://localhost:${port}`);
 
-  await connect();
+  connect();
 });
diff --git a/src/utils/connect.ts b/src/utils/connect.ts
index a6a4831..7d2b0c8 100644
--- a/src/utils/connect.ts
+++ b/src/utils/connect.ts
@@ -2,11 +2,11 @@ import mongoose from "mongoose";
 import config from "config";
 import logger from "./logger";
 
-async function connect() {
+function connect() {
   const dbUri = config.get<string>("dbUri");
 
   try {
-    await mongoose.connect(dbUri);
+    mongoose.connect(dbUri);
     logger.info("DB connected");
   } catch (error) {
     logger.error("Could not connect to db");
```

Once you make this change, you run into the same jwt malformed issue #1 followed by a new error (`ERROR: MongooseError: Operation 'users.insertOne()' buffering timed out after 10000ms`) after creating a user with Postman:

```
> rest-api-tutorial-updated@1.0.0 dev
> ts-node-dev --respawn --transpile-only src/app.ts

[INFO] 03:36:33 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.3)
[2021-10-24T03:36:34+01:00] INFO: App is running at http://localhost:1337
[2021-10-24T03:36:34+01:00] INFO: DB connected
JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (/Users/phil/dev/Testing-Express-REST-API/node_modules/jsonwebtoken/verify.js:63:17)
    at verifyJwt (/Users/phil/dev/Testing-Express-REST-API/src/utils/jwt.utils.ts:16:25)
    at /Users/phil/dev/Testing-Express-REST-API/src/middleware/deserializeUser.ts:22:41
    at step (/Users/phil/dev/Testing-Express-REST-API/src/middleware/deserializeUser.ts:33:23)
    at Object.next (/Users/phil/dev/Testing-Express-REST-API/src/middleware/deserializeUser.ts:14:53)
    at /Users/phil/dev/Testing-Express-REST-API/src/middleware/deserializeUser.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/phil/dev/Testing-Express-REST-API/src/middleware/deserializeUser.ts:4:12)
    at deserializeUser (/Users/phil/dev/Testing-Express-REST-API/src/middleware/deserializeUser.ts:9:21)
    at Layer.handle [as handle_request] (/Users/phil/dev/Testing-Express-REST-API/node_modules/express/lib/router/layer.js:95:5)
[2021-10-24T03:36:53+01:00] ERROR: MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    Error: MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
        at /Users/phil/dev/Testing-Express-REST-API/src/service/user.service.ts:15:11
        at step (/Users/phil/dev/Testing-Express-REST-API/src/service/user.service.ts:33:23)
        at Object.throw (/Users/phil/dev/Testing-Express-REST-API/src/service/user.service.ts:14:53)
        at rejected (/Users/phil/dev/Testing-Express-REST-API/src/service/user.service.ts:6:65)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at NativeConnection.Connection.openUri (/Users/phil/dev/Testing-Express-REST-API/node_modules/mongoose/lib/connection.js:796:32)
    at /Users/phil/dev/Testing-Express-REST-API/node_modules/mongoose/lib/index.js:328:10
    at /Users/phil/dev/Testing-Express-REST-API/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/phil/dev/Testing-Express-REST-API/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/Users/phil/dev/Testing-Express-REST-API/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/Users/phil/dev/Testing-Express-REST-API/node_modules/mongoose/lib/index.js:327:20)
    at connect (/Users/phil/dev/Testing-Express-REST-API/src/utils/connect.ts:9:14)
    at Server.<anonymous> (/Users/phil/dev/Testing-Express-REST-API/src/app.ts:14:10)
    at Object.onceWrapper (node:events:509:28)
[ERROR] 03:37:04 MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
```

**Comment by replete** [comment]
Looks like others are having issues with Mongoose and Node 17: 
[cant connect to DB with Node v17](https://github.com/Automattic/mongoose/issues/10917)

**Comment by treysis** [comment]
MongoDB needs to be started/configured with `net.ipv6` set to `true`.
